### ISSUE TITLE
combine download_data and download_any_ble_data into one function?? alternatively, how to structure download capabilities?

### ISSUE THREAD

**Issue by atn38** [BLE-LTER/BLEdatatools#22]
Combining the two would improve consistency and coherence in our product, plus ease in developing downstream functions. relates to #8

how I imagine the combined function will work:

download_data takes an additional function, tentatively named "zip" and defaults to FALSE.

if zip == FALSE:
download_data proceeds as normal and gets the CSVs for collation
if users specify IDs not in collation plan, then what? One idea is to give zip files for non-collate IDs and the CSVs/R objects for the rest. IDK. 

if zip == TRUE:
download_data then becomes download_any_ble_data and just gives the zip files and NO R objects.

@bristol-emily @alinaCO2spera: I'd appreciate your input on this.

**Comment by twhiteaker** [comment]
If the result is an easily-understood function, then hooray. If the resulting function differs enough in behavior depending on the value of function parameters that it confuses users, then it may be better to have separate functions.

**Comment by atn38** [comment]
Thanks for your input @twhiteaker. For context, download_any_ble_data is from #8. There has already been some confusion within our group (the people writing this package!) between the two, which is the motivation for combining.

**Comment by alinaCO2spera** [comment]
I think this is what you are saying @atn38, and is what I now think is the best solution: 
- Collate will download the data and collate, user can ask for or exclude certain packageids but it is the CP collation data only, plus option to write csvs of raw data. 
- Download will be a way to get any and all packages as zipped files?

**Comment by atn38** [comment]
ok we're doing this now! download just downloads collate just collates

**Comment by bristol-emily** [comment]
What should we rename our general/flexible download function as (currently named download_any_ble_data)? The function is currently working (for one package or entity at a time). One renamed, are we ready to merge this function and search_ble_packages function into the development branch?

**Comment by atn38** [comment]
@bristol-emily I was just working on moving stuff around, see the commit above. The old `download_data` is no more, so that's up for grabs. Merging is fine. I'd like the download function to be more robust (more checks for invalid arguments as we discussed yesterday), but that can happen before or after merging, up to you.

**Comment by atn38** [comment]
I think we're done here
