### ISSUE TITLE
idea: add message in download_data that returns the name of packages the user specified in argument

### ISSUE THREAD

**Issue by bristol-emily** [BLE-LTER/BLEdatatools#7]
Also possibly the names of the entities they are downloading. Would we code this into decide_entities?

Relates to issue #3

**Comment by atn38** [comment]
relates #3

**Comment by atn38** [comment]
I've thought about a related idea: you know sometimes when you update a package and messages show up on the console asking you which other packages to also update? Something similar for us. Or even a pop-up window that asks the user to check boxes next to datasets they want, but this makes it too much of a GUI so I'm not sure.

**Comment by bristol-emily** [comment]
download_data() has this functionality now (provides a message with the title of package or entity the user specified)
