### ISSUE TITLE
idea: Do we want a function that can download files not included in our plan for a collated spreadsheet?

### ISSUE THREAD

**Issue by bristol-emily** [BLE-LTER/BLEdatatools#8]
Or is this beyond the scope of our project?

**Comment by atn38** [comment]
I've thought about this a bit more, and imo let's go for it. I can think of several functions for similar purposes in other packages, but having it bundled in BLEdatatools will be helpful for BLE people.

**Comment by bristol-emily** [comment]
Consider adding an option to save entities as R objects rather than writing a csv.

**Comment by bristol-emily** [comment]
Created a function that can download any package (zip file) or .csv file. This function is now called download_data().
